version: '3.3'

services:
  # 主应用服务
  nxlink-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: nxlink-webtools:${TAG:-latest}
    container_name: nxlink-webtools
    restart: unless-stopped
    ports:
      - "${GATEWAY_PORT:-8350}:8350"  # 网关端口
      - "${BACKEND_PORT:-8450}:8450"  # 后端端口
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT:-8450}
      - BACKEND_PORT=${BACKEND_PORT:-8450}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:8350}
      - JWT_SECRET=${JWT_SECRET:-please-change-this-jwt-secret}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-ChangeMe123!}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # OpenAPI配置
      - OPENAPI_ACCESS_KEY=${OPENAPI_ACCESS_KEY:-}
      - OPENAPI_ACCESS_SECRET=${OPENAPI_ACCESS_SECRET:-}
      - DOCKER_CONTAINER=true
      - OPENAPI_BIZ_TYPE=${OPENAPI_BIZ_TYPE:-8}
      - OPENAPI_BASE_URL=${OPENAPI_BASE_URL:-https://api-westus.nxlink.ai}
    volumes:
      - ./logs:/app/logs:rw
      - ./server/config:/app/server/config:rw
      - ./uploads:/app/uploads:rw
    depends_on: []
    networks:
      - nxlink-network

networks:
  nxlink-network:
    driver: bridge
