curl 'https://app.nxlink.ai/admin/saas_plat/user/is_login' \
  -X 'PUT' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en,zh;q=0.9,zh-CN;q=0.8,fil;q=0.7,de;q=0.6' \
  -H 'authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1SWQiOjIyLCJkZXZpY2VVbmlxdWVJZGVudGlmaWNhdGlvbiI6IjVmZTdiNjcwLWMxMjAtMTFlZi1hOWM1LTI1YTA0MDM0OWQ5YiIsInV1SWQiOiI2OGE2ZTAwOGU0YjAxZmFkYjJhODhjYWEifQ.RDQ7Uzhax7wBuaNc4ayZcffh2fTW4s24pT4t14vJ-g4' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 0' \
  -b 'nx-utc=UTC+08:00; nx-zone=105; company_domain=null; locale=zh-CN; company_domain=null; plat_token=eyJhbGciOiJIUzI1NiJ9.eyJ1SWQiOjIyLCJkZXZpY2VVbmlxdWVJZGVudGlmaWNhdGlvbiI6IjVmZTdiNjcwLWMxMjAtMTFlZi1hOWM1LTI1YTA0MDM0OWQ5YiIsInV1SWQiOiI2OGE2ZTAwOGU0YjAxZmFkYjJhODhjYWEifQ.RDQ7Uzhax7wBuaNc4ayZcffh2fTW4s24pT4t14vJ-g4; isLogin=1; JSESSIONID=9C475C37C0EEADBCA9E3E1DE4341CF87' \
  -H 'createts: 1755766792953' \
  -H 'currentdomain: app.nxlink.ai' \
  -H 'dnt: 1' \
  -H 'lang: zh_CN' \
  -H 'origin: https://app.nxlink.ai' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'referer: https://app.nxlink.ai/admin/' \
  -H 'sec-ch-ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'system_id: 5' \
  -H 'time_zone: UTC+08:00' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36'

  #Response

  {
    "code": 0,
    "message": "",
    "data": {
        "state": 1,
        "userInfo": {
            "id": 22,
            "phone": "8617770033772",
            "email": "xu.xunjian@nxcloud.com",
            "nickname": "徐勋健",
            "company": "NX77777178086-牛信产研部-深圳",
            "defaultTenantId": 1,
            "customerId": 9622,
            "customerCode": "NX77777178086",
            "customerType": 3,
            "roleName": "管理员",
            "tenantName": "营销云租户（内部使用）",
            "tenantNickName": "勋健",
            "systemRoles": [
                {
                    "system_id": 2,
                    "role_id": 5,
                    "role_name": "管理员",
                    "tenant_id": null,
                    "role_unique_key": null,
                    "is_default": null
                },
                {
                    "system_id": 1,
                    "role_id": 2,
                    "role_name": "管理员",
                    "tenant_id": null,
                    "role_unique_key": null,
                    "is_default": null
                },
                {
                    "system_id": 5,
                    "role_id": 36,
                    "role_name": "管理员",
                    "tenant_id": null,
                    "role_unique_key": "8",
                    "is_default": 1
                }
            ],
            "source": 0,
            "shaPwd": null,
            "uuid": "68a6e008e4b01fadb2a88caa"
        },
        "isLoginUser": null,
        "isTenantOwner": false,
        "textSeat": true,
        "voiceSeat": true,
        "bundleExpire": false,
        "currency": "USD",
        "companyDomain": null,
        "loginType": null,
        "tokenRemainSec": 17999
    },
    "traceId": "cb2550f20ff344ceb3f7c87bd8e41ce3"
}