curl 'https://nxlink.nxcloud.com/admin/saas_plat/user/is_login' \
  -X 'PUT' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en,zh;q=0.9,zh-CN;q=0.8,fil;q=0.7,de;q=0.6' \
  -H 'authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1SWQiOjg0MjgsImRldmljZVVuaXF1ZUlkZW50aWZpY2F0aW9uIjoiOTA1YjQ3NjAtNDkwNS0xMWVmLWJlNDEtOTc5MjkwYTA3YjY2IiwidXVJZCI6IjY4MDlmYTAzZTRiMDE4ZjBmNDU4NjUyNCJ9.qaln5Qkt44X1P2Ix549wXAM_wLlBObJwd54lVmnehdw' \
  -H 'cache-control: no-cache' \
  -H 'content-length: 0' \
  -H 'createts: 1745570906555' \
  -H 'currentdomain: nxlink.nxcloud.com' \
  -H 'dnt: 1' \
  -H 'lang: zh_CN' \
  -H 'origin: https://nxlink.nxcloud.com' \
  -H 'pragma: no-cache' \
  -H 'priority: u=1, i' \
  -H 'referer: https://nxlink.nxcloud.com/admin/' \
  -H 'sec-ch-ua: "Google Chrome";v="135", "Not-A.Brand";v="8", "Chromium";v="135"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'system_id: 5' \
  -H 'time_zone: UTC+08:00' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36'

  # response
  {
    "code": 0,
    "message": "",
    "data": {
        "state": 1,
        "userInfo": {
            "id": 8428,
            "phone": "85255311705",
            "email": "degenxu@nxcloud.com",
            "nickname": "Degen-DEV",
            "company": "NX777777001086-WhatsApp内部测试用",
            "defaultTenantId": 4,
            "customerId": 12882,
            "customerCode": "NX777777001086",
            "customerType": null,
            "roleName": "客服专员",
            "tenantName": "客户测试环境（勿删）",
            "tenantNickName": "Degenxu@nxcloud.com",
            "systemRoles": [
                {
                    "system_id": 1,
                    "role_id": 3,
                    "role_name": "客服专员",
                    "tenant_id": null,
                    "role_unique_key": null,
                    "is_default": null
                },
                {
                    "system_id": 5,
                    "role_id": 57,
                    "role_name": "管理员",
                    "tenant_id": null,
                    "role_unique_key": "8",
                    "is_default": 1
                }
            ],
            "source": 0,
            "shaPwd": "866abc45472bd0c0a06029620420c0e6",
            "uuid": "6809fa03e4b018f0f4586524"
        },
        "isLoginUser": null,
        "isTenantOwner": false,
        "textSeat": true,
        "voiceSeat": true,
        "bundleExpire": false,
        "currency": "CNY",
        "companyDomain": null,
        "loginType": null,
        "tokenRemainSec": 17999
    },
    "traceId": "fa75d9fee1b24fcd9729c295bc05b423"
}