curl 'https://nxlink.nxcloud.com/admin/nx_flow_manager/mgrPlatform/sceneInfo?shared=true&page_number=1&page_size=10&nxCloudUserID=9622&tenantId=1&type=2&show_all=false' \
-X 'GET' \
-H 'Pragma: no-cache' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1SWQiOjgxNywidXVJZCI6IjY5MjdhNmIxZTRiMGQyY2M3MGM3N2MwZiJ9.BCW7gbEyTsDqC2lgVRQIPlPqEyh6osHsoA0yw5dhafo' \
-H 'Sec-Fetch-Site: same-origin' \
-H 'Accept-Language: zh-CN,zh-Hans;q=0.9' \
-H 'Cache-Control: no-cache' \
-H 'Sec-Fetch-Mode: cors' \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'Host: nxlink.nxcloud.com' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15' \
-H 'Referer: https://nxlink.nxcloud.com/admin/manager/' \
-H 'Connection: keep-alive' \
-H 'Sec-Fetch-Dest: empty' \
-H 'lang: zh_CN' \
-H 'system_id: 4'

{
    "code": 0,
    "message": "success",
    "traceId": "09b715f757b645b3b97807d473358255",
    "data": {
        "code": 0,
        "message": null,
        "traceId": null,
        "total": 3245,
        "page_number": 1,
        "page_size": 10,
        "list": [
            {
                "id": 16539,
                "type": 2,
                "language": "ru-RU",
                "vendor": "16",
                "vendor_params": "{\"name\":\"defualt\",\"id\":\"e78c48255508ddfd577f\",\"model\":\"multilingual_v3\",\"quality\":\"0\"}",
                "code": "Omega",
                "timbre": "defualt",
                "model": "multilingual_v3",
                "vendor_app_id": "66",
                "status": 1,
                "rating": "Standard",
                "remark": "",
                "create_ts": 0,
                "update_ts": 1763359603,
                "flags": 0,
                "clone_url": null,
                "tenant_ids": null,
                "clone_msg": null,
                "create_by_tenant_id": null,
                "shared": true
            },
            {
                "id": 16540,
                "type": 2,
                "language": "de-DE",
                "vendor": "16",
                "vendor_params": "{\"name\":\"defualt\",\"id\":\"e78c48255508ddfd577f\",\"model\":\"multilingual_v3\",\"quality\":\"0\"}",
                "code": "Omega",
                "timbre": "defualt",
                "model": "multilingual_v3",
                "vendor_app_id": "66",
                "status": 1,
                "rating": "Standard",
                "remark": "",
                "create_ts": 0,
                "update_ts": 1763359602,
                "flags": 0,
                "clone_url": null,
                "tenant_ids": null,
                "clone_msg": null,
                "create_by_tenant_id": null,
                "shared": true
            },
            {
                "id": 16542,
                "type": 2,
                "language": "ja-JP",
                "vendor": "16",
                "vendor_params": "{\"name\":\"defualt\",\"id\":\"e78c48255508ddfd577f\",\"model\":\"multilingual_v3\",\"quality\":\"0\"}",
                "code": "Omega",
                "timbre": "defualt",
                "model": "multilingual_v3",
                "vendor_app_id": "66",
                "status": 1,
                "rating": "Standard",
                "remark": "",
                "create_ts": 0,
                "update_ts": 1763359601,
                "flags": 0,
                "clone_url": null,
                "tenant_ids": null,
                "clone_msg": null,
                "create_by_tenant_id": null,
                "shared": true
            },
            {
                "id": 16541,
                "type": 2,
                "language": "it-IT",
                "vendor": "16",
                "vendor_params": "{\"name\":\"defualt\",\"id\":\"e78c48255508ddfd577f\",\"model\":\"multilingual_v3\",\"quality\":\"0\"}",
                "code": "Omega",
                "timbre": "defualt",
                "model": "multilingual_v3",
                "vendor_app_id": "66",
                "status": 1,
                "rating": "Standard",
                "remark": "",
                "create_ts": 0,
                "update_ts": 1763359601,
                "flags": 0,
                "clone_url": null,
                "tenant_ids": null,
                "clone_msg": null,
                "create_by_tenant_id": null,
                "shared": true
            },
            {
                "id": 16544,
                "type": 2,
                "language": "en-US",
                "vendor": "16",
                "vendor_params": "{\"name\":\"defualt\",\"id\":\"e78c48255508ddfd577f\",\"model\":\"multilingual_v3\",\"quality\":\"0\"}",
                "code": "Omega",
                "timbre": "defualt",
                "model": "multilingual_v3",
                "vendor_app_id": "66",
                "status": 1,
                "rating": "Standard",
                "remark": "",
                "create_ts": 0,
                "update_ts": 1763359600,
                "flags": 0,
                "clone_url": null,
                "tenant_ids": null,
                "clone_msg": null,
                "create_by_tenant_id": null,
                "shared": true
            },
            {
                "id": 16543,
                "type": 2,
                "language": "fr-FR",
                "vendor": "16",
                "vendor_params": "{\"name\":\"defualt\",\"id\":\"e78c48255508ddfd577f\",\"model\":\"multilingual_v3\",\"quality\":\"0\"}",
                "code": "Omega",
                "timbre": "defualt",
                "model": "multilingual_v3",
                "vendor_app_id": "66",
                "status": 1,
                "rating": "Standard",
                "remark": "",
                "create_ts": 0,
                "update_ts": 1763359600,
                "flags": 0,
                "clone_url": null,
                "tenant_ids": null,
                "clone_msg": null,
                "create_by_tenant_id": null,
                "shared": true
            },
            {
                "id": 16545,
                "type": 2,
                "language": "pt-PT",
                "vendor": "16",
                "vendor_params": "{\"name\":\"defualt\",\"id\":\"e78c48255508ddfd577f\",\"model\":\"multilingual_v3\",\"quality\":\"0\"}",
                "code": "Omega",
                "timbre": "defualt",
                "model": "multilingual_v3",
                "vendor_app_id": "66",
                "status": 1,
                "rating": "Standard",
                "remark": "",
                "create_ts": 0,
                "update_ts": 1763359599,
                "flags": 0,
                "clone_url": null,
                "tenant_ids": null,
                "clone_msg": null,
                "create_by_tenant_id": null,
                "shared": true
            },
            {
                "id": 16547,
                "type": 2,
                "language": "ko-KR",
                "vendor": "16",
                "vendor_params": "{\"name\":\"defualt\",\"id\":\"e78c48255508ddfd577f\",\"model\":\"multilingual_v3\",\"quality\":\"0\"}",
                "code": "Omega",
                "timbre": "defualt",
                "model": "multilingual_v3",
                "vendor_app_id": "66",
                "status": 1,
                "rating": "Standard",
                "remark": "",
                "create_ts": 0,
                "update_ts": 1763359598,
                "flags": 0,
                "clone_url": null,
                "tenant_ids": null,
                "clone_msg": null,
                "create_by_tenant_id": null,
                "shared": true
            },
            {
                "id": 16546,
                "type": 2,
                "language": "es-ES",
                "vendor": "16",
                "vendor_params": "{\"name\":\"defualt\",\"id\":\"e78c48255508ddfd577f\",\"model\":\"multilingual_v3\",\"quality\":\"0\"}",
                "code": "Omega",
                "timbre": "defualt",
                "model": "multilingual_v3",
                "vendor_app_id": "66",
                "status": 1,
                "rating": "Standard",
                "remark": "",
                "create_ts": 0,
                "update_ts": 1763359598,
                "flags": 0,
                "clone_url": null,
                "tenant_ids": null,
                "clone_msg": null,
                "create_by_tenant_id": null,
                "shared": true
            },
            {
                "id": 16548,
                "type": 2,
                "language": "da-DK",
                "vendor": "16",
                "vendor_params": "{\"name\":\"defualt\",\"id\":\"e78c48255508ddfd577f\",\"model\":\"multilingual_v3\",\"quality\":\"0\"}",
                "code": "Omega",
                "timbre": "defualt",
                "model": "multilingual_v3",
                "vendor_app_id": "66",
                "status": 1,
                "rating": "Standard",
                "remark": "",
                "create_ts": 0,
                "update_ts": 1763359597,
                "flags": 0,
                "clone_url": null,
                "tenant_ids": null,
                "clone_msg": null,
                "create_by_tenant_id": null,
                "shared": true
            }
        ],
        "ext": null,
        "notEmpty": true,
        "totalPages": 3245,
        "empty": false
    }
}